import { TokenCountProvider } from '@/components/token';
import { Metadata } from "next";
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

const title = 'snowbrain';
const description = 'Generated by create next app';

export const metadata: Metadata = {
  title,
  description,
  openGraph: {
    title,
    description,
  },
  twitter: {
    title,
    description,
    card: "summary_large_image",
    creator: "@kaarthikcodes",
  },
  metadataBase: new URL("https://snowbrain.vercel.app/"),
  themeColor: "#ffffff",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <TokenCountProvider>
        <body className={inter.className}><Toaster />{children}</body>
      </TokenCountProvider>
    </html>
  )
}
